### ISSUE TITLE
Hey i cant download your latest release : Missing Permissions when trying to download

### ISSUE THREAD

**Issue by yannickfelle** [usefulstuffs/SEBPatch#1]
could you help me resolve this problem? Or grand me permission to use your project?

**Comment by yannickfelle** [comment]
![Screenshot_2](https://github.com/user-attachments/assets/4c123469-022a-4c8f-9e40-22b17e9bd466)

**Comment by usefulstuffs** [comment]
Hello there! I just managed to download the executable from my secondary machine (where I was not logged in) and it downloaded successfully. Can you please try disabling the antivirus and download the file again?

![image](https://github.com/user-attachments/assets/5912474b-391d-4204-a24e-ec0ccdb3102a)

**Comment by yannickfelle** [comment]
hey so i did try a diffrent browser and without anti virus (also not logged in)
Sadly same problem 
![Neu](https://github.com/user-attachments/assets/3e71f3a5-bbec-47d4-9360-ae34f955ed1e)

**Comment by yannickfelle** [comment]
Sure gonna try tomorrow thankyou. will reply after testing :)

**Comment by yannickfelle** [comment]
it did work thankyou very much
can i spend you a coffe or something?

**Comment by usefulstuffs** [comment]
> it did work thankyou very much can i spend you a coffe or something?
> 
> and can i also run seb with this on a vm?

It should work also on a VM.
Happy that you got it working!
